version: "3.8"

services:
  postgress:
    image: postgres:16.1-alpine3.18
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: school
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgresql://admin:admin@localhost:5432/school
    container_name: nextjs_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
